### ISSUE TITLE
Tutorials are (sometimes) not accessible behind corporate firewalls

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/GSoD#2]
**Project name**: add tutorial slides as PDF download links to tutorials page

**Description**: Tutorials are now in google drive, and this is (sometimes) not accessible behind corporate firewalls. Would be great if a download link can be provided next to the iframes that now host the google docs.

**Comment by tmazor** [comment]
@pieterlukasse I think we can take care of this one ourselves, no need to wait for GSoD. I'll make a new issue and assign myself.

**Comment by pieterlukasse** [comment]
@tmazor thanks!

**Comment by pieterlukasse** [comment]
@tmazor can you please also link the issue here? Then I can share it with the people interested in following its progress. Thanks!

**Comment by tmazor** [comment]
@pieterlukasse the new issue is here: https://github.com/cBioPortal/cbioportal/issues/5989
